/*
 * Akamai: Linode API
 *
 * Add a Cloud Computing instance so you can build, release, and scale applications faster with virtual machines. 
 *
 * The version of the OpenAPI document: 4.193.0
 * Contact: jperez@linode.com
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration};


/// struct for typed errors of method [`delete_lke_cluster_acl`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteLkeClusterAclError {
    Status400(models::GetLkeClusterAcl400Response),
    Status404(models::GetLkeClusterAcl404Response),
    DefaultResponse(models::GetAccountDefaultResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_lke_cluster_acl`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetLkeClusterAclError {
    Status400(models::GetLkeClusterAcl400Response),
    Status404(models::GetLkeClusterAcl404Response),
    DefaultResponse(models::GetAccountDefaultResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`put_lke_cluster_acl`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PutLkeClusterAclError {
    Status400(models::GetLkeClusterAcl400Response),
    Status404(models::GetLkeClusterAcl404Response),
    DefaultResponse(models::GetAccountDefaultResponse),
    UnknownValue(serde_json::Value),
}


/// Disable control plane access controls and deletes all rules. This has the same effect as calling `PUT` with an acl json map value of `{“enabled” : false}`. __Note__: control plane ACLs may not currently be available to all users.   <<LB>>  ---   - __CLI__.      ```     linode-cli lke cluster-acl-delete 12345     ```      [Learn more...](https://techdocs.akamai.com/cloud-computing/docs/getting-started-with-the-linode-cli)  - __OAuth scopes__.      ```     lke:read_write     ```      [Learn more...](https://techdocs.akamai.com/linode-api/reference/get-started#oauth)
pub async fn delete_lke_cluster_acl(configuration: &configuration::Configuration, api_version: &str, cluster_id: i32) -> Result<serde_json::Value, Error<DeleteLkeClusterAclError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_api_version = api_version;
    let p_cluster_id = cluster_id;

    let uri_str = format!("{}/{apiVersion}/lke/clusters/{clusterId}/control_plane_acl", configuration.base_path, apiVersion=crate::apis::urlencode(p_api_version), clusterId=p_cluster_id);
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        serde_json::from_str(&content).map_err(Error::from)
    } else {
        let content = resp.text().await?;
        let entity: Option<DeleteLkeClusterAclError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Get a specific cluster's control plane access control List. __Note__: control plane ACLs may not currently be available to all users.   <<LB>>  ---   - __CLI__.      ```     linode-cli lke cluster-acl-view 12345     ```      [Learn more...](https://techdocs.akamai.com/cloud-computing/docs/getting-started-with-the-linode-cli)  - __OAuth scopes__.      ```     lke:read_only     ```      [Learn more...](https://techdocs.akamai.com/linode-api/reference/get-started#oauth)
pub async fn get_lke_cluster_acl(configuration: &configuration::Configuration, api_version: &str, cluster_id: i32) -> Result<models::GetLkeClusterAcl200Response, Error<GetLkeClusterAclError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_api_version = api_version;
    let p_cluster_id = cluster_id;

    let uri_str = format!("{}/{apiVersion}/lke/clusters/{clusterId}/control_plane_acl", configuration.base_path, apiVersion=crate::apis::urlencode(p_api_version), clusterId=p_cluster_id);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        serde_json::from_str(&content).map_err(Error::from)
    } else {
        let content = resp.text().await?;
        let entity: Option<GetLkeClusterAclError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Updates a specific cluster's control plane access control list. __Note__: control plane ACLs may not currently be available to all users.   <<LB>>  ---   - __CLI__.      ```     linode-cli lke cluster-acl-update 12345 \\       --acl.enabled true \\       --acl.addresses.ipv4 \"203.0.113.1\" \\       --acl.addresses.ipv6 \"2001:db8:1234:abcd::/64\"     ```      [Learn more...](https://techdocs.akamai.com/cloud-computing/docs/getting-started-with-the-linode-cli)  - __OAuth scopes__.      ```     lke:read_write     ```      [Learn more...](https://techdocs.akamai.com/linode-api/reference/get-started#oauth)
pub async fn put_lke_cluster_acl(configuration: &configuration::Configuration, api_version: &str, cluster_id: i32, put_lke_cluster_acl_request: Option<models::PutLkeClusterAclRequest>) -> Result<models::PutLkeClusterAcl200Response, Error<PutLkeClusterAclError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_api_version = api_version;
    let p_cluster_id = cluster_id;
    let p_put_lke_cluster_acl_request = put_lke_cluster_acl_request;

    let uri_str = format!("{}/{apiVersion}/lke/clusters/{clusterId}/control_plane_acl", configuration.base_path, apiVersion=crate::apis::urlencode(p_api_version), clusterId=p_cluster_id);
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_put_lke_cluster_acl_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        serde_json::from_str(&content).map_err(Error::from)
    } else {
        let content = resp.text().await?;
        let entity: Option<PutLkeClusterAclError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

