/*
 * Akamai: Linode API
 *
 * Add a Cloud Computing instance so you can build, release, and scale applications faster with virtual machines. 
 *
 * The version of the OpenAPI document: 4.193.0
 * Contact: jperez@linode.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AddedPostBetaProgram : The Beta Program ID to enroll in for your Account.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddedPostBetaProgram {
    /// The unique identifier of the Beta Program.
    #[serde(rename = "id")]
    pub id: String,
}

impl AddedPostBetaProgram {
    /// The Beta Program ID to enroll in for your Account.
    pub fn new(id: String) -> AddedPostBetaProgram {
        AddedPostBetaProgram {
            id,
        }
    }
}

