/*
 * Akamai: Linode API
 *
 * Add a Cloud Computing instance so you can build, release, and scale applications faster with virtual machines. 
 *
 * The version of the OpenAPI document: 4.193.0
 * Contact: jperez@linode.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetLinodeIps200ResponseIpv6GlobalInner : An object representing an IPv6 range.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetLinodeIps200ResponseIpv6GlobalInner {
    /// The prefix length of the address. The total number of addresses that can be assigned from this range is calculated as 2<sup>(128 - prefix length)</sup>.
    #[serde(rename = "prefix", skip_serializing_if = "Option::is_none")]
    pub prefix: Option<i32>,
    /// __Read-only__ The IPv6 address of this range.
    #[serde(rename = "range", skip_serializing_if = "Option::is_none")]
    pub range: Option<String>,
    /// __Read-only__ The region for this range of IPv6 addresses.
    #[serde(rename = "region", skip_serializing_if = "Option::is_none")]
    pub region: Option<String>,
    /// The IPv6 SLAAC address.
    #[serde(rename = "route_target", skip_serializing_if = "Option::is_none")]
    pub route_target: Option<String>,
}

impl GetLinodeIps200ResponseIpv6GlobalInner {
    /// An object representing an IPv6 range.
    pub fn new() -> GetLinodeIps200ResponseIpv6GlobalInner {
        GetLinodeIps200ResponseIpv6GlobalInner {
            prefix: None,
            range: None,
            region: None,
            route_target: None,
        }
    }
}

