/*
 * Akamai: Linode API
 *
 * Add a Cloud Computing instance so you can build, release, and scale applications faster with virtual machines. 
 *
 * The version of the OpenAPI document: 4.193.0
 * Contact: jperez@linode.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetDatabasesTypes200ResponseAllOfDataInnerEnginesMysqlInnerPrice : Cost in US dollars, broken down into hourly and monthly charges.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetDatabasesTypes200ResponseAllOfDataInnerEnginesMysqlInnerPrice {
    /// Cost (in US dollars) per hour for this subscription tier.
    #[serde(rename = "hourly", skip_serializing_if = "Option::is_none")]
    pub hourly: Option<f64>,
    /// Maximum cost (in US dollars) per month for this subscription tier.
    #[serde(rename = "monthly", skip_serializing_if = "Option::is_none")]
    pub monthly: Option<f64>,
}

impl GetDatabasesTypes200ResponseAllOfDataInnerEnginesMysqlInnerPrice {
    /// Cost in US dollars, broken down into hourly and monthly charges.
    pub fn new() -> GetDatabasesTypes200ResponseAllOfDataInnerEnginesMysqlInnerPrice {
        GetDatabasesTypes200ResponseAllOfDataInnerEnginesMysqlInnerPrice {
            hourly: None,
            monthly: None,
        }
    }
}

