/*
 * Akamai: Linode API
 *
 * Add a Cloud Computing instance so you can build, release, and scale applications faster with virtual machines. 
 *
 * The version of the OpenAPI document: 4.193.0
 * Contact: jperez@linode.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetLinodeStats200ResponseNetv6 : IPv6 statistics.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetLinodeStats200ResponseNetv6 {
    /// Input stats for IPv6, measured in bits/s (bits/second).
    #[serde(rename = "in", skip_serializing_if = "Option::is_none")]
    pub r#in: Option<Vec<Vec<f64>>>,
    /// Output stats for IPv6, measured in bits/s (bits/second).
    #[serde(rename = "out", skip_serializing_if = "Option::is_none")]
    pub out: Option<Vec<Vec<f64>>>,
    /// Private IPv6 input statistics, measured in bits/s (bits/second).
    #[serde(rename = "private_in", skip_serializing_if = "Option::is_none")]
    pub private_in: Option<Vec<Vec<f64>>>,
    /// Private IPv6 output statistics, measured in bits/s (bits/second).
    #[serde(rename = "private_out", skip_serializing_if = "Option::is_none")]
    pub private_out: Option<Vec<Vec<f64>>>,
}

impl GetLinodeStats200ResponseNetv6 {
    /// IPv6 statistics.
    pub fn new() -> GetLinodeStats200ResponseNetv6 {
        GetLinodeStats200ResponseNetv6 {
            r#in: None,
            out: None,
            private_in: None,
            private_out: None,
        }
    }
}

