/*
 * Akamai: Linode API
 *
 * Add a Cloud Computing instance so you can build, release, and scale applications faster with virtual machines. 
 *
 * The version of the OpenAPI document: 4.193.0
 * Contact: jperez@linode.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetLkeClusterApiEndpoints200ResponseDataInner {
    /// __Read-only__ A Kubernetes API server endpoint for this cluster.
    #[serde(rename = "endpoint", skip_serializing_if = "Option::is_none")]
    pub endpoint: Option<String>,
}

impl GetLkeClusterApiEndpoints200ResponseDataInner {
    pub fn new() -> GetLkeClusterApiEndpoints200ResponseDataInner {
        GetLkeClusterApiEndpoints200ResponseDataInner {
            endpoint: None,
        }
    }
}

