/*
 * Akamai: Linode API
 *
 * Add a Cloud Computing instance so you can build, release, and scale applications faster with virtual machines. 
 *
 * The version of the OpenAPI document: 4.193.0
 * Contact: jperez@linode.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetEvents200ResponseDataInnerSecondaryEntity : __Read-only__ Detailed information about the Event's secondary entity, which provides additional information for events such as, but not limited to, `linode_boot`, `linode_reboot`, `linode_create`, and `linode_clone` Event actions.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetEvents200ResponseDataInnerSecondaryEntity {
    /// The ID of the object that is the secondary entity.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The label of this object.
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    /// __Read-only__ The type of entity that is being referenced by the Event.
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    /// The URL where you can access the object this Event is for. If a relative URL, it is relative to the domain you retrieved the Event from.
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

impl GetEvents200ResponseDataInnerSecondaryEntity {
    /// __Read-only__ Detailed information about the Event's secondary entity, which provides additional information for events such as, but not limited to, `linode_boot`, `linode_reboot`, `linode_create`, and `linode_clone` Event actions.
    pub fn new() -> GetEvents200ResponseDataInnerSecondaryEntity {
        GetEvents200ResponseDataInnerSecondaryEntity {
            id: None,
            label: None,
            r#type: None,
            url: None,
        }
    }
}

