/*
 * Akamai: Linode API
 *
 * Add a Cloud Computing instance so you can build, release, and scale applications faster with virtual machines. 
 *
 * The version of the OpenAPI document: 4.193.0
 * Contact: jperez@linode.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum GetTaggedObjects200ResponseDataInnerData {
    #[serde(rename="Linode_7")]
    Linode7(models::Linode7),
    #[serde(rename="Domain_2")]
    Domain2(models::Domain2),
    #[serde(rename="Volume_1")]
    Volume1(models::Volume1),
    #[serde(rename="NodeBalancer_6")]
    NodeBalancer6(models::NodeBalancer6),
}

impl Default for GetTaggedObjects200ResponseDataInnerData {
    fn default() -> Self {
        Self::Linode7(Default::default())
    }
}

/// __Read-only__ The virtualization software powering this Linode.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum HypervisorEnum {
    #[serde(rename = "kvm")]
    Kvm,
}

impl Default for HypervisorEnum {
    fn default() -> HypervisorEnum {
        Self::Kvm
    }
}
/// __Read-only__ The current status of the volume.  Can be one of:    - `creating`. The volume is being created and is not yet available for use.   - `active`. The volume is online and available for use.   - `resizing`. The volume is in the process of upgrading its current capacity.   - `key_rotating`. The volume is in the process of rotating encryption keys. Requests to resize, delete, or clone a volume fails during encryption key rotation.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum StatusEnum {
    #[serde(rename = "creating")]
    Creating,
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "resizing")]
    Resizing,
    #[serde(rename = "key_rotating")]
    KeyRotating,
}

impl Default for StatusEnum {
    fn default() -> StatusEnum {
        Self::Creating
    }
}
/// __Limited availability__, __Read-only__ Displays if encryption is enabled on this volume.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EncryptionEnum {
    #[serde(rename = "enabled")]
    Enabled,
    #[serde(rename = "disabled")]
    Disabled,
}

impl Default for EncryptionEnum {
    fn default() -> EncryptionEnum {
        Self::Enabled
    }
}
/// __Read-only__ The storage type of this Volume.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum HardwareTypeEnum {
    #[serde(rename = "hdd")]
    Hdd,
    #[serde(rename = "nvme")]
    Nvme,
}

impl Default for HardwareTypeEnum {
    fn default() -> HardwareTypeEnum {
        Self::Hdd
    }
}

