/*
 * Akamai: Linode API
 *
 * Add a Cloud Computing instance so you can build, release, and scale applications faster with virtual machines. 
 *
 * The version of the OpenAPI document: 4.193.0
 * Contact: jperez@linode.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetManagedIssues200ResponseDataInner : An Issue that was detected with a service Linode is managing.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetManagedIssues200ResponseDataInner {
    /// __Read-only__ When this Issue was created. Issues are created in response to issues detected with Managed Services, so this is also when the Issue was detected.
    #[serde(rename = "created", skip_serializing_if = "Option::is_none")]
    pub created: Option<String>,
    #[serde(rename = "entity", skip_serializing_if = "Option::is_none")]
    pub entity: Option<models::GetManagedIssues200ResponseDataInnerEntity>,
    /// __Read-only__ This Issue's unique ID.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// __Read-only__ An array of Managed Service IDs that were affected by this Issue.
    #[serde(rename = "services", skip_serializing_if = "Option::is_none")]
    pub services: Option<Vec<i32>>,
}

impl GetManagedIssues200ResponseDataInner {
    /// An Issue that was detected with a service Linode is managing.
    pub fn new() -> GetManagedIssues200ResponseDataInner {
        GetManagedIssues200ResponseDataInner {
            created: None,
            entity: None,
            id: None,
            services: None,
        }
    }
}

