/*
 * Akamai: Linode API
 *
 * Add a Cloud Computing instance so you can build, release, and scale applications faster with virtual machines. 
 *
 * The version of the OpenAPI document: 4.193.0
 * Contact: jperez@linode.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetFirewallDevices200ResponseDataInnerEntity : __Read-only__ The compute service that this Firewall has been applied to.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetFirewallDevices200ResponseDataInnerEntity {
    /// The entity's ID.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// __Read-only__ The entity's label.
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    /// The entity's type.
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<TypeEnum>,
    /// __Read-only__ The API URL path you can use to access this entity.
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

impl GetFirewallDevices200ResponseDataInnerEntity {
    /// __Read-only__ The compute service that this Firewall has been applied to.
    pub fn new() -> GetFirewallDevices200ResponseDataInnerEntity {
        GetFirewallDevices200ResponseDataInnerEntity {
            id: None,
            label: None,
            r#type: None,
            url: None,
        }
    }
}
/// The entity's type.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TypeEnum {
    #[serde(rename = "linode")]
    Linode,
    #[serde(rename = "nodebalancer")]
    Nodebalancer,
}

impl Default for TypeEnum {
    fn default() -> TypeEnum {
        Self::Linode
    }
}

