/*
 * Akamai: Linode API
 *
 * Add a Cloud Computing instance so you can build, release, and scale applications faster with virtual machines. 
 *
 * The version of the OpenAPI document: 4.193.0
 * Contact: jperez@linode.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetDatabasesMysqlInstanceCredentials200Response : Managed Database object for database credentials.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetDatabasesMysqlInstanceCredentials200Response {
    /// __Read-only__ The randomly generated root password for the Managed Database instance.
    #[serde(rename = "password", skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,
    /// __Read-only__ The root username for the Managed Database instance.
    #[serde(rename = "username", skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
}

impl GetDatabasesMysqlInstanceCredentials200Response {
    /// Managed Database object for database credentials.
    pub fn new() -> GetDatabasesMysqlInstanceCredentials200Response {
        GetDatabasesMysqlInstanceCredentials200Response {
            password: None,
            username: None,
        }
    }
}

