/*
 * Akamai: Linode API
 *
 * Add a Cloud Computing instance so you can build, release, and scale applications faster with virtual machines. 
 *
 * The version of the OpenAPI document: 4.193.0
 * Contact: jperez@linode.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetNetworkTransferPrices200ResponseDataInnerRegionPricesInner {
    /// Cost per hour for this region, in US dollars.
    #[serde(rename = "hourly", skip_serializing_if = "Option::is_none")]
    pub hourly: Option<f64>,
    /// The Region ID for these prices.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Cost per month for this region, in US dollars.
    #[serde(rename = "monthly", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub monthly: Option<Option<f64>>,
}

impl GetNetworkTransferPrices200ResponseDataInnerRegionPricesInner {
    pub fn new() -> GetNetworkTransferPrices200ResponseDataInnerRegionPricesInner {
        GetNetworkTransferPrices200ResponseDataInnerRegionPricesInner {
            hourly: None,
            id: None,
            monthly: None,
        }
    }
}

