/*
 * Akamai: Linode API
 *
 * Add a Cloud Computing instance so you can build, release, and scale applications faster with virtual machines. 
 *
 * The version of the OpenAPI document: 4.193.0
 * Contact: jperez@linode.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetIpv6Range200Response : An object representing an IPv6 range.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetIpv6Range200Response {
    /// __Read-only__ Whether this IPv6 range is shared.
    #[serde(rename = "is_bgp", skip_serializing_if = "Option::is_none")]
    pub is_bgp: Option<bool>,
    /// __Read-only__ A list of Linodes targeted by this IPv6 range. Includes Linodes with IP sharing.
    #[serde(rename = "linodes", skip_serializing_if = "Option::is_none")]
    pub linodes: Option<Vec<i32>>,
    /// The prefix length of the address. The total number of addresses that can be assigned from this range is calculated as 2<sup>(128 - prefix length)</sup>.
    #[serde(rename = "prefix", skip_serializing_if = "Option::is_none")]
    pub prefix: Option<i32>,
    /// __Read-only__ The IPv6 address of this range.
    #[serde(rename = "range", skip_serializing_if = "Option::is_none")]
    pub range: Option<String>,
    /// __Read-only__ The region for this range of IPv6 addresses.
    #[serde(rename = "region", skip_serializing_if = "Option::is_none")]
    pub region: Option<String>,
}

impl GetIpv6Range200Response {
    /// An object representing an IPv6 range.
    pub fn new() -> GetIpv6Range200Response {
        GetIpv6Range200Response {
            is_bgp: None,
            linodes: None,
            prefix: None,
            range: None,
            region: None,
        }
    }
}

