/*
 * Akamai: Linode API
 *
 * Add a Cloud Computing instance so you can build, release, and scale applications faster with virtual machines. 
 *
 * The version of the OpenAPI document: 4.193.0
 * Contact: jperez@linode.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetTicketReplies200ResponseDataInner : An object representing a reply to a support ticket.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetTicketReplies200ResponseDataInner {
    /// __Read-only__ When this ticket reply was created.
    #[serde(rename = "created", skip_serializing_if = "Option::is_none")]
    pub created: Option<String>,
    /// __Read-only__ The user who submitted this reply.
    #[serde(rename = "created_by", skip_serializing_if = "Option::is_none")]
    pub created_by: Option<String>,
    /// __Read-only__ The body of this support ticket reply.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// __Read-only__ If `true`, this reply came from a Linode employee.
    #[serde(rename = "from_linode", skip_serializing_if = "Option::is_none")]
    pub from_linode: Option<bool>,
    /// __Read-only__ The Gravatar ID of the user who created this reply.
    #[serde(rename = "gravatar_id", skip_serializing_if = "Option::is_none")]
    pub gravatar_id: Option<String>,
    /// __Read-only__ The unique ID of this support ticket reply.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
}

impl GetTicketReplies200ResponseDataInner {
    /// An object representing a reply to a support ticket.
    pub fn new() -> GetTicketReplies200ResponseDataInner {
        GetTicketReplies200ResponseDataInner {
            created: None,
            created_by: None,
            description: None,
            from_linode: None,
            gravatar_id: None,
            id: None,
        }
    }
}

