/*
 * Akamai: Linode API
 *
 * Add a Cloud Computing instance so you can build, release, and scale applications faster with virtual machines. 
 *
 * The version of the OpenAPI document: 4.193.0
 * Contact: jperez@linode.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetDatabasesTypes200ResponseAllOfDataInnerEngines {
    /// Pricing details for MySQL Managed Databases.
    #[serde(rename = "mysql", skip_serializing_if = "Option::is_none")]
    pub mysql: Option<Vec<models::GetDatabasesTypes200ResponseAllOfDataInnerEnginesMysqlInner>>,
    /// Pricing details for PostgreSQL Managed Databases.
    #[serde(rename = "postgresql", skip_serializing_if = "Option::is_none")]
    pub postgresql: Option<Vec<models::GetDatabasesTypes200ResponseAllOfDataInnerEnginesMysqlInner>>,
}

impl GetDatabasesTypes200ResponseAllOfDataInnerEngines {
    pub fn new() -> GetDatabasesTypes200ResponseAllOfDataInnerEngines {
        GetDatabasesTypes200ResponseAllOfDataInnerEngines {
            mysql: None,
            postgresql: None,
        }
    }
}

