/*
 * Akamai: Linode API
 *
 * Add a Cloud Computing instance so you can build, release, and scale applications faster with virtual machines. 
 *
 * The version of the OpenAPI document: 4.193.0
 * Contact: jperez@linode.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetNodeBalancerStats200Response : Stats for this NodeBalancer.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetNodeBalancerStats200Response {
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<models::GetNodeBalancerStats200ResponseData>,
    /// The title for the statistics generated in this response.
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
}

impl GetNodeBalancerStats200Response {
    /// Stats for this NodeBalancer.
    pub fn new() -> GetNodeBalancerStats200Response {
        GetNodeBalancerStats200Response {
            data: None,
            title: None,
        }
    }
}

