/*
 * Akamai: Linode API
 *
 * Add a Cloud Computing instance so you can build, release, and scale applications faster with virtual machines. 
 *
 * The version of the OpenAPI document: 4.193.0
 * Contact: jperez@linode.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetDatabasesMysqlInstanceSsl200Response : Managed Database SSL object.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetDatabasesMysqlInstanceSsl200Response {
    /// The base64-encoded SSL CA certificate for the Managed Database instance.
    #[serde(rename = "ca_certificate", skip_serializing_if = "Option::is_none")]
    pub ca_certificate: Option<String>,
}

impl GetDatabasesMysqlInstanceSsl200Response {
    /// Managed Database SSL object.
    pub fn new() -> GetDatabasesMysqlInstanceSsl200Response {
        GetDatabasesMysqlInstanceSsl200Response {
            ca_certificate: None,
        }
    }
}

