/*
 * Akamai: Linode API
 *
 * Add a Cloud Computing instance so you can build, release, and scale applications faster with virtual machines. 
 *
 * The version of the OpenAPI document: 4.193.0
 * Contact: jperez@linode.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetPaymentMethods200ResponseDataInnerData {
    CreditCard(models::CreditCard),
    GooglePay(models::GooglePay),
    Paypal(models::Paypal),
}

impl Default for GetPaymentMethods200ResponseDataInnerData {
    fn default() -> Self {
        Self::CreditCard(Default::default())
    }
}

