/*
 * Akamai: Linode API
 *
 * Add a Cloud Computing instance so you can build, release, and scale applications faster with virtual machines. 
 *
 * The version of the OpenAPI document: 4.193.0
 * Contact: jperez@linode.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetSecurityQuestions200ResponseSecurityQuestionsInner : Single security question and response object for GET operation.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetSecurityQuestions200ResponseSecurityQuestionsInner {
    /// The ID representing the security question.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// __Read-only__ The security question.
    #[serde(rename = "question", skip_serializing_if = "Option::is_none")]
    pub question: Option<String>,
    /// The security question response.
    #[serde(rename = "response", skip_serializing_if = "Option::is_none")]
    pub response: Option<String>,
}

impl GetSecurityQuestions200ResponseSecurityQuestionsInner {
    /// Single security question and response object for GET operation.
    pub fn new() -> GetSecurityQuestions200ResponseSecurityQuestionsInner {
        GetSecurityQuestions200ResponseSecurityQuestionsInner {
            id: None,
            question: None,
            response: None,
        }
    }
}

