/*
 * Akamai: Linode API
 *
 * Add a Cloud Computing instance so you can build, release, and scale applications faster with virtual machines. 
 *
 * The version of the OpenAPI document: 4.193.0
 * Contact: jperez@linode.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetLongviewClients200ResponseDataInner : A LongviewClient is a single monitor set up to track statistics about one of your servers.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetLongviewClients200ResponseDataInner {
    /// __Read-only__ The API key for this Client, used when configuring the Longview Client application on your Linode.  Returns as `[REDACTED]` if you do not have read-write access to this client.
    #[serde(rename = "api_key", skip_serializing_if = "Option::is_none")]
    pub api_key: Option<String>,
    #[serde(rename = "apps", skip_serializing_if = "Option::is_none")]
    pub apps: Option<models::GetLongviewClients200ResponseDataInnerApps>,
    /// __Read-only__ When this Longview Client was created.
    #[serde(rename = "created", skip_serializing_if = "Option::is_none")]
    pub created: Option<String>,
    /// __Read-only__ This Client's unique ID.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// __Read-only__ The install code for this Client, used when configuring the Longview Client application on your Linode.  Returns as `[REDACTED]` if you do not have read-write access to this client.
    #[serde(rename = "install_code", skip_serializing_if = "Option::is_none")]
    pub install_code: Option<String>,
    /// __Filterable__ This Client's unique label. This is for display purposes only.
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    /// __Read-only__ When this Longview Client was last updated.
    #[serde(rename = "updated", skip_serializing_if = "Option::is_none")]
    pub updated: Option<String>,
}

impl GetLongviewClients200ResponseDataInner {
    /// A LongviewClient is a single monitor set up to track statistics about one of your servers.
    pub fn new() -> GetLongviewClients200ResponseDataInner {
        GetLongviewClients200ResponseDataInner {
            api_key: None,
            apps: None,
            created: None,
            id: None,
            install_code: None,
            label: None,
            updated: None,
        }
    }
}

