/*
 * Akamai: Linode API
 *
 * Add a Cloud Computing instance so you can build, release, and scale applications faster with virtual machines. 
 *
 * The version of the OpenAPI document: 4.193.0
 * Contact: jperez@linode.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetRegions200ResponseDataInnerResolvers {
    /// __Read-only__ The IPv4 addresses for this region's DNS resolvers, separated by commas.
    #[serde(rename = "ipv4", skip_serializing_if = "Option::is_none")]
    pub ipv4: Option<String>,
    /// __Read-only__ The IPv6 addresses for this region's DNS resolvers, separated by commas.
    #[serde(rename = "ipv6", skip_serializing_if = "Option::is_none")]
    pub ipv6: Option<String>,
}

impl GetRegions200ResponseDataInnerResolvers {
    pub fn new() -> GetRegions200ResponseDataInnerResolvers {
        GetRegions200ResponseDataInnerResolvers {
            ipv4: None,
            ipv6: None,
        }
    }
}

