/*
 * Akamai: Linode API
 *
 * Add a Cloud Computing instance so you can build, release, and scale applications faster with virtual machines. 
 *
 * The version of the OpenAPI document: 4.193.0
 * Contact: jperez@linode.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetLongviewPlan200Response : A Longview Subscription represents a tier of Longview service you can subscribe to.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetLongviewPlan200Response {
    /// __Read-only__ The number of Longview Clients that may be created with this Subscription tier.
    #[serde(rename = "clients_included", skip_serializing_if = "Option::is_none")]
    pub clients_included: Option<i32>,
    /// __Read-only__ The unique ID of this Subscription tier.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<IdEnum>,
    /// __Read-only__ A display name for this Subscription tier.
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    #[serde(rename = "price", skip_serializing_if = "Option::is_none")]
    pub price: Option<models::GetLongviewPlan200ResponsePrice>,
}

impl GetLongviewPlan200Response {
    /// A Longview Subscription represents a tier of Longview service you can subscribe to.
    pub fn new() -> GetLongviewPlan200Response {
        GetLongviewPlan200Response {
            clients_included: None,
            id: None,
            label: None,
            price: None,
        }
    }
}
/// __Read-only__ The unique ID of this Subscription tier.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum IdEnum {
    #[serde(rename = "longview-3")]
    Longview3,
    #[serde(rename = "longview-10")]
    Longview10,
    #[serde(rename = "longview-40")]
    Longview40,
    #[serde(rename = "longview-100")]
    Longview100,
}

impl Default for IdEnum {
    fn default() -> IdEnum {
        Self::Longview3
    }
}

