/*
 * Akamai: Linode API
 *
 * Add a Cloud Computing instance so you can build, release, and scale applications faster with virtual machines. 
 *
 * The version of the OpenAPI document: 4.193.0
 * Contact: jperez@linode.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetVolumeTypes200ResponseDataInnerPrice : __Read-only__ The default cost of this volume type. Prices are in US dollars, broken down into hourly and monthly charges.  Certain regions have different prices from the default. For region-specific prices, see `region_prices`.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetVolumeTypes200ResponseDataInnerPrice {
    /// __Filterable__ Cost (in US dollars) per hour.
    #[serde(rename = "hourly", skip_serializing_if = "Option::is_none")]
    pub hourly: Option<f64>,
    /// __Filterable__ Cost per month, in US dollars.
    #[serde(rename = "monthly", skip_serializing_if = "Option::is_none")]
    pub monthly: Option<f64>,
}

impl GetVolumeTypes200ResponseDataInnerPrice {
    /// __Read-only__ The default cost of this volume type. Prices are in US dollars, broken down into hourly and monthly charges.  Certain regions have different prices from the default. For region-specific prices, see `region_prices`.
    pub fn new() -> GetVolumeTypes200ResponseDataInnerPrice {
        GetVolumeTypes200ResponseDataInnerPrice {
            hourly: None,
            monthly: None,
        }
    }
}

