/*
 * Akamai: Linode API
 *
 * Add a Cloud Computing instance so you can build, release, and scale applications faster with virtual machines. 
 *
 * The version of the OpenAPI document: 4.193.0
 * Contact: jperez@linode.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetKernels200ResponseDataInner : Linux kernel object.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetKernels200ResponseDataInner {
    /// __Filterable__, __Read-only__ The architecture of this Kernel.
    #[serde(rename = "architecture", skip_serializing_if = "Option::is_none")]
    pub architecture: Option<ArchitectureEnum>,
    /// __Read-only__ The date on which this Kernel was built.
    #[serde(rename = "built", skip_serializing_if = "Option::is_none")]
    pub built: Option<String>,
    /// __Filterable__, __Read-only__ If this Kernel is marked as deprecated, this field has a value of `true`; otherwise, this field is `false`.
    #[serde(rename = "deprecated", skip_serializing_if = "Option::is_none")]
    pub deprecated: Option<bool>,
    /// __Read-only__ The unique ID of this Kernel.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// __Filterable__, __Read-only__ If this Kernel is suitable for KVM Linodes.
    #[serde(rename = "kvm", skip_serializing_if = "Option::is_none")]
    pub kvm: Option<bool>,
    /// __Filterable__, __Read-only__ The friendly name of this Kernel.
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    /// __Filterable__, __Read-only__ If this Kernel is suitable for paravirtualized operations.
    #[serde(rename = "pvops", skip_serializing_if = "Option::is_none")]
    pub pvops: Option<bool>,
    /// __Filterable__, __Read-only__ Linux Kernel version.
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
}

impl GetKernels200ResponseDataInner {
    /// Linux kernel object.
    pub fn new() -> GetKernels200ResponseDataInner {
        GetKernels200ResponseDataInner {
            architecture: None,
            built: None,
            deprecated: None,
            id: None,
            kvm: None,
            label: None,
            pvops: None,
            version: None,
        }
    }
}
/// __Filterable__, __Read-only__ The architecture of this Kernel.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ArchitectureEnum {
    #[serde(rename = "x86_64")]
    X8664,
    #[serde(rename = "i386")]
    I386,
}

impl Default for ArchitectureEnum {
    fn default() -> ArchitectureEnum {
        Self::X8664
    }
}

