/*
 * Akamai: Linode API
 *
 * Add a Cloud Computing instance so you can build, release, and scale applications faster with virtual machines. 
 *
 * The version of the OpenAPI document: 4.193.0
 * Contact: jperez@linode.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetObjectStorageEndpoints200ResponseAllOfDataInner : Object Storage endpoints object.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetObjectStorageEndpoints200ResponseAllOfDataInner {
    /// __Read-only__ The type of `s3_endpoint` available to the active `user` in this `region`. See [Endpoint types](https://techdocs.akamai.com/cloud-computing/docs/object-storage#endpoint-type) for more information.
    #[serde(rename = "endpoint_type", skip_serializing_if = "Option::is_none")]
    pub endpoint_type: Option<EndpointTypeEnum>,
    /// __Read-only__ The Akamai cloud computing region, represented by its slug value. Run the [List regions](https://techdocs.akamai.com/linode-api/reference/get-regions) operation to view all regions and their slugs.
    #[serde(rename = "region", skip_serializing_if = "Option::is_none")]
    pub region: Option<String>,
    /// __Read-only__ Your s3 endpoint URL, based on the `endpoint_type` and `region`. Displayed as `null` if you haven't assigned an endpoint for your user.
    #[serde(rename = "s3_endpoint", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub s3_endpoint: Option<Option<String>>,
}

impl GetObjectStorageEndpoints200ResponseAllOfDataInner {
    /// Object Storage endpoints object.
    pub fn new() -> GetObjectStorageEndpoints200ResponseAllOfDataInner {
        GetObjectStorageEndpoints200ResponseAllOfDataInner {
            endpoint_type: None,
            region: None,
            s3_endpoint: None,
        }
    }
}
/// __Read-only__ The type of `s3_endpoint` available to the active `user` in this `region`. See [Endpoint types](https://techdocs.akamai.com/cloud-computing/docs/object-storage#endpoint-type) for more information.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EndpointTypeEnum {
    #[serde(rename = "E0")]
    E0,
    #[serde(rename = "E1")]
    E1,
    #[serde(rename = "E2")]
    E2,
    #[serde(rename = "E3")]
    E3,
}

impl Default for EndpointTypeEnum {
    fn default() -> EndpointTypeEnum {
        Self::E0
    }
}

