/*
 * Akamai: Linode API
 *
 * Add a Cloud Computing instance so you can build, release, and scale applications faster with virtual machines. 
 *
 * The version of the OpenAPI document: 4.193.0
 * Contact: jperez@linode.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "x-linode-ref-name")]
pub enum GetManagedStats200ResponseData {
    #[serde(rename="Stats_available")]
    StatsAvailable(models::StatsAvailable),
    /// __Read-only__ An array of error messages if managed stats are unavailable.
    #[serde(rename="one_of_1")]
    StatsUnavailable(Vec<String>),
}

impl Default for GetManagedStats200ResponseData {
    fn default() -> Self {
        Self::StatsAvailable(Default::default())
    }
}


