/*
 * Akamai: Linode API
 *
 * Add a Cloud Computing instance so you can build, release, and scale applications faster with virtual machines. 
 *
 * The version of the OpenAPI document: 4.193.0
 * Contact: jperez@linode.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetStackScripts200ResponseDataInnerUserDefinedFieldsInner : A custom field defined by the User with a special syntax within a StackScript. Derived from the contents of the script.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetStackScripts200ResponseDataInnerUserDefinedFieldsInner {
    /// __Read-only__ The default value.  If not specified, this value will be used.
    #[serde(rename = "default", skip_serializing_if = "Option::is_none")]
    pub default: Option<String>,
    /// __Read-only__ An example value for the field.
    #[serde(rename = "example")]
    pub example: String,
    /// __Read-only__ A human-readable label for the field that will serve as the input prompt for entering the value during deployment.
    #[serde(rename = "label")]
    pub label: String,
    /// __Read-only__ A list of acceptable values for the field in any quantity, combination or order.
    #[serde(rename = "manyOf", skip_serializing_if = "Option::is_none")]
    pub many_of: Option<String>,
    /// __Read-only__ The name of the field.
    #[serde(rename = "name")]
    pub name: String,
    /// __Read-only__ A list of acceptable single values for the field.
    #[serde(rename = "oneOf", skip_serializing_if = "Option::is_none")]
    pub one_of: Option<String>,
}

impl GetStackScripts200ResponseDataInnerUserDefinedFieldsInner {
    /// A custom field defined by the User with a special syntax within a StackScript. Derived from the contents of the script.
    pub fn new(example: String, label: String, name: String) -> GetStackScripts200ResponseDataInnerUserDefinedFieldsInner {
        GetStackScripts200ResponseDataInnerUserDefinedFieldsInner {
            default: None,
            example,
            label,
            many_of: None,
            name,
            one_of: None,
        }
    }
}

