/*
 * Akamai: Linode API
 *
 * Add a Cloud Computing instance so you can build, release, and scale applications faster with virtual machines. 
 *
 * The version of the OpenAPI document: 4.193.0
 * Contact: jperez@linode.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetBackups200ResponseSnapshot {
    #[serde(rename = "current", skip_serializing_if = "Option::is_none")]
    pub current: Option<models::GetBackups200ResponseSnapshotCurrent>,
    #[serde(rename = "in_progress", skip_serializing_if = "Option::is_none")]
    pub in_progress: Option<models::GetBackups200ResponseSnapshotCurrent>,
}

impl GetBackups200ResponseSnapshot {
    pub fn new() -> GetBackups200ResponseSnapshot {
        GetBackups200ResponseSnapshot {
            current: None,
            in_progress: None,
        }
    }
}

