/*
 * Akamai: Linode API
 *
 * Add a Cloud Computing instance so you can build, release, and scale applications faster with virtual machines. 
 *
 * The version of the OpenAPI document: 4.193.0
 * Contact: jperez@linode.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetStackScripts200ResponseDataInner : A StackScript enables you to quickly deploy a fully configured application in an automated manner.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetStackScripts200ResponseDataInner {
    /// __Read-only__ The date this StackScript was created.
    #[serde(rename = "created", skip_serializing_if = "Option::is_none")]
    pub created: Option<String>,
    /// __Read-only__ Count of currently active, deployed Linodes created from this StackScript.
    #[serde(rename = "deployments_active", skip_serializing_if = "Option::is_none")]
    pub deployments_active: Option<i32>,
    /// __Filterable__, __Read-only__ The total number of times this StackScript has been deployed.
    #[serde(rename = "deployments_total", skip_serializing_if = "Option::is_none")]
    pub deployments_total: Option<i32>,
    /// __Filterable__ A description for the StackScript.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// __Read-only__ The unique ID of this StackScript.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// An array of Image IDs. These are the Images that can be deployed with this StackScript.  `any/all` indicates that all available Images, including private Images, are accepted.
    #[serde(rename = "images", skip_serializing_if = "Option::is_none")]
    pub images: Option<Vec<String>>,
    /// __Filterable__ This determines whether other users can use your StackScript. __Once a StackScript is made public, it cannot be made private.__
    #[serde(rename = "is_public", skip_serializing_if = "Option::is_none")]
    pub is_public: Option<bool>,
    /// __Filterable__ The StackScript's label is for display purposes only.
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    /// __Filterable__, __Read-only__ Returns `true` if this StackScript is owned by the account of the user making the request, and the user making the request is unrestricted or has access to this StackScript.
    #[serde(rename = "mine", skip_serializing_if = "Option::is_none")]
    pub mine: Option<bool>,
    /// __Filterable__ This field allows you to add notes for the set of revisions made to this StackScript.
    #[serde(rename = "rev_note", skip_serializing_if = "Option::is_none")]
    pub rev_note: Option<String>,
    /// The script to execute when provisioning a new Linode with this StackScript.
    #[serde(rename = "script", skip_serializing_if = "Option::is_none")]
    pub script: Option<String>,
    /// __Read-only__ The date this StackScript was last updated.
    #[serde(rename = "updated", skip_serializing_if = "Option::is_none")]
    pub updated: Option<String>,
    /// __Read-only__ This is a list of fields defined with a special syntax inside this StackScript that allow for supplying customized parameters during deployment. See [Declare User-Defined Fields (UDFs)](https://www.linode.com/docs/products/tools/stackscripts/guides/write-a-custom-script/#declare-user-defined-fields-udfs) for more information.
    #[serde(rename = "user_defined_fields", skip_serializing_if = "Option::is_none")]
    pub user_defined_fields: Option<Vec<models::GetStackScripts200ResponseDataInnerUserDefinedFieldsInner>>,
    /// __Read-only__ The Gravatar ID for the User who created the StackScript.
    #[serde(rename = "user_gravatar_id", skip_serializing_if = "Option::is_none")]
    pub user_gravatar_id: Option<String>,
    /// __Read-only__ The User who created the StackScript.
    #[serde(rename = "username", skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
}

impl GetStackScripts200ResponseDataInner {
    /// A StackScript enables you to quickly deploy a fully configured application in an automated manner.
    pub fn new() -> GetStackScripts200ResponseDataInner {
        GetStackScripts200ResponseDataInner {
            created: None,
            deployments_active: None,
            deployments_total: None,
            description: None,
            id: None,
            images: None,
            is_public: None,
            label: None,
            mine: None,
            rev_note: None,
            script: None,
            updated: None,
            user_defined_fields: None,
            user_gravatar_id: None,
            username: None,
        }
    }
}

