/*
 * Akamai: Linode API
 *
 * Add a Cloud Computing instance so you can build, release, and scale applications faster with virtual machines. 
 *
 * The version of the OpenAPI document: 4.193.0
 * Contact: jperez@linode.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PostReplicateImageRequest : List of regions where the image should be replicated to.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostReplicateImageRequest {
    /// The unique identifier for each compute `region`. See [Regions and images](https://techdocs.akamai.com/cloud-computing/docs/images#regions-and-images) for full details on support for `regions`.
    #[serde(rename = "regions", skip_serializing_if = "Option::is_none")]
    pub regions: Option<Vec<String>>,
}

impl PostReplicateImageRequest {
    /// List of regions where the image should be replicated to.
    pub fn new() -> PostReplicateImageRequest {
        PostReplicateImageRequest {
            regions: None,
        }
    }
}

