/*
 * Akamai: Linode API
 *
 * Add a Cloud Computing instance so you can build, release, and scale applications faster with virtual machines. 
 *
 * The version of the OpenAPI document: 4.193.0
 * Contact: jperez@linode.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostRescueLinodeInstanceRequestDevices {
    #[serde(rename = "sda", skip_serializing_if = "Option::is_none")]
    pub sda: Option<models::GetLinodeConfigs200ResponseDataInnerDevicesSda>,
    #[serde(rename = "sdb", skip_serializing_if = "Option::is_none")]
    pub sdb: Option<models::GetLinodeConfigs200ResponseDataInnerDevicesSda>,
    #[serde(rename = "sdc", skip_serializing_if = "Option::is_none")]
    pub sdc: Option<models::GetLinodeConfigs200ResponseDataInnerDevicesSda>,
    #[serde(rename = "sdd", skip_serializing_if = "Option::is_none")]
    pub sdd: Option<models::GetLinodeConfigs200ResponseDataInnerDevicesSda>,
    #[serde(rename = "sde", skip_serializing_if = "Option::is_none")]
    pub sde: Option<models::GetLinodeConfigs200ResponseDataInnerDevicesSda>,
    #[serde(rename = "sdf", skip_serializing_if = "Option::is_none")]
    pub sdf: Option<models::GetLinodeConfigs200ResponseDataInnerDevicesSda>,
    #[serde(rename = "sdg", skip_serializing_if = "Option::is_none")]
    pub sdg: Option<models::GetLinodeConfigs200ResponseDataInnerDevicesSda>,
}

impl PostRescueLinodeInstanceRequestDevices {
    pub fn new() -> PostRescueLinodeInstanceRequestDevices {
        PostRescueLinodeInstanceRequestDevices {
            sda: None,
            sdb: None,
            sdc: None,
            sdd: None,
            sde: None,
            sdf: None,
            sdg: None,
        }
    }
}

