/*
 * Akamai: Linode API
 *
 * Add a Cloud Computing instance so you can build, release, and scale applications faster with virtual machines. 
 *
 * The version of the OpenAPI document: 4.193.0
 * Contact: jperez@linode.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PostFirewallsRequestDevices : Devices to create for this Firewall. When a Device is created, the Firewall is assigned to its associated service. Currently, Devices can be created for Linode compute instances and NodeBalancers.  Additional devices can be assigned after Firewall creation by using the [Create a firewall device](https://techdocs.akamai.com/linode-api/reference/post-firewall-device) operation.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostFirewallsRequestDevices {
    /// An array of Linode IDs. A Firewall Device is created for each ID.
    #[serde(rename = "linodes", skip_serializing_if = "Option::is_none")]
    pub linodes: Option<Vec<i32>>,
    /// An array containing a NodeBalancer ID. A Firewall Device is created for the ID.  - A NodeBalancer can have only one Firewall assigned to it. - Firewalls only apply to inbound TCP traffic to NodeBalancers.
    #[serde(rename = "nodebalancers", skip_serializing_if = "Option::is_none")]
    pub nodebalancers: Option<Vec<i32>>,
}

impl PostFirewallsRequestDevices {
    /// Devices to create for this Firewall. When a Device is created, the Firewall is assigned to its associated service. Currently, Devices can be created for Linode compute instances and NodeBalancers.  Additional devices can be assigned after Firewall creation by using the [Create a firewall device](https://techdocs.akamai.com/linode-api/reference/post-firewall-device) operation.
    pub fn new() -> PostFirewallsRequestDevices {
        PostFirewallsRequestDevices {
            linodes: None,
            nodebalancers: None,
        }
    }
}

