/*
 * Akamai: Linode API
 *
 * Add a Cloud Computing instance so you can build, release, and scale applications faster with virtual machines. 
 *
 * The version of the OpenAPI document: 4.193.0
 * Contact: jperez@linode.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostTfaConfirm200Response {
    /// A one-use code that can be used in place of your Two Factor code, in case you are unable to generate one.  Keep this in a safe place to avoid being locked out of your Account.
    #[serde(rename = "scratch", skip_serializing_if = "Option::is_none")]
    pub scratch: Option<String>,
}

impl PostTfaConfirm200Response {
    pub fn new() -> PostTfaConfirm200Response {
        PostTfaConfirm200Response {
            scratch: None,
        }
    }
}

