/*
 * Akamai: Linode API
 *
 * Add a Cloud Computing instance so you can build, release, and scale applications faster with virtual machines. 
 *
 * The version of the OpenAPI document: 4.193.0
 * Contact: jperez@linode.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostCloneVolumeRequest {
    /// __Filterable__ The Volume's label is for display purposes only.
    #[serde(rename = "label")]
    pub label: String,
}

impl PostCloneVolumeRequest {
    pub fn new(label: String) -> PostCloneVolumeRequest {
        PostCloneVolumeRequest {
            label,
        }
    }
}

