/*
 * Akamai: Linode API
 *
 * Add a Cloud Computing instance so you can build, release, and scale applications faster with virtual machines. 
 *
 * The version of the OpenAPI document: 4.193.0
 * Contact: jperez@linode.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PostVpcSubnetRequest : VPC Subnet Create request object.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostVpcSubnetRequest {
    /// IPv4 range in CIDR canonical form.  - The range must belong to a private address space as defined in [RFC1918](https://datatracker.ietf.org/doc/html/rfc1918). - Allowed prefix lengths: 1-29. - The range must not overlap with 192.168.128.0/17. - The range must not overlap with other Subnets on the same VPC.
    #[serde(rename = "ipv4")]
    pub ipv4: String,
    /// __Filterable__ The VPC Subnet's label, for display purposes only.  - Must be unique among the VPC's Subnets. - Can only contain ASCII letters, numbers, and hyphens (`-`). You can't use two consecutive hyphens (`--`).
    #[serde(rename = "label")]
    pub label: String,
}

impl PostVpcSubnetRequest {
    /// VPC Subnet Create request object.
    pub fn new(ipv4: String, label: String) -> PostVpcSubnetRequest {
        PostVpcSubnetRequest {
            ipv4,
            label,
        }
    }
}

