/*
 * Akamai: Linode API
 *
 * Add a Cloud Computing instance so you can build, release, and scale applications faster with virtual machines. 
 *
 * The version of the OpenAPI document: 4.193.0
 * Contact: jperez@linode.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PostObjectStorageSslRequest : Upload a TLS/SSL certificate and private key to be served when you visit your Object Storage bucket via HTTPS.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostObjectStorageSslRequest {
    /// Your Base64 encoded and PEM formatted SSL certificate.  Line breaks must be represented as `\\n` in the string for requests (but not when using the Linode CLI)
    #[serde(rename = "certificate")]
    pub certificate: String,
    /// The private key associated with this TLS/SSL certificate.  Line breaks must be represented as `\\n` in the string for requests (but not when using the Linode CLI)
    #[serde(rename = "private_key")]
    pub private_key: String,
}

impl PostObjectStorageSslRequest {
    /// Upload a TLS/SSL certificate and private key to be served when you visit your Object Storage bucket via HTTPS.
    pub fn new(certificate: String, private_key: String) -> PostObjectStorageSslRequest {
        PostObjectStorageSslRequest {
            certificate,
            private_key,
        }
    }
}

