/*
 * Akamai: Linode API
 *
 * Add a Cloud Computing instance so you can build, release, and scale applications faster with virtual machines. 
 *
 * The version of the OpenAPI document: 4.193.0
 * Contact: jperez@linode.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostUploadImage200Response {
    #[serde(rename = "image", skip_serializing_if = "Option::is_none")]
    pub image: Option<models::GetImages200ResponseDataInner>,
    /// The URL to upload the Image to.
    #[serde(rename = "upload_to", skip_serializing_if = "Option::is_none")]
    pub upload_to: Option<String>,
}

impl PostUploadImage200Response {
    pub fn new() -> PostUploadImage200Response {
        PostUploadImage200Response {
            image: None,
            upload_to: None,
        }
    }
}

