/*
 * Akamai: Linode API
 *
 * Add a Cloud Computing instance so you can build, release, and scale applications faster with virtual machines. 
 *
 * The version of the OpenAPI document: 4.193.0
 * Contact: jperez@linode.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PostDatabasesMysqlInstancesRequest : Managed MySQL Database request object.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostDatabasesMysqlInstancesRequest {
    /// Controls access to the Managed Database.  - Individually included IP addresses or CIDR ranges can access the Managed Database while all other sources are blocked.  - A standalone value of `0.0.0.0/0` allows all IP addresses access to the Managed Database.  - An empty array (`[]`) blocks all public and private connections to the Managed Database.
    #[serde(rename = "allow_list", skip_serializing_if = "Option::is_none")]
    pub allow_list: Option<Vec<String>>,
    /// The number of Linode instance nodes deployed to the Managed Database.   - Choose `3` nodes to create a high availability cluster that consists of one primary node and two replica nodes.  - A `2` node cluster is only available with a dedicated plan. It consists of one primary node and one replica node.
    #[serde(rename = "cluster_size", skip_serializing_if = "Option::is_none")]
    pub cluster_size: Option<ClusterSizeEnum>,
    /// The Managed Database engine in engine/version format.
    #[serde(rename = "engine")]
    pub engine: String,
    #[serde(rename = "fork", skip_serializing_if = "Option::is_none")]
    pub fork: Option<models::PostDatabasesMysqlInstancesRequestFork>,
    /// __Filterable__ A unique, user-defined string referring to the Managed Database. This string needs to be unique per Managed Database engine type.
    #[serde(rename = "label")]
    pub label: String,
    /// __Filterable__ The [Region](https://techdocs.akamai.com/linode-api/reference/get-regions) ID for the Managed Database.
    #[serde(rename = "region")]
    pub region: String,
    /// Currently required to be `true`. Whether to require SSL credentials to establish a connection to the Managed Database.  Run the [Get managed MySQL database credentials](https://techdocs.akamai.com/linode-api/reference/get-databases-mysql-instance-credentials) operation for access information.
    #[serde(rename = "ssl_connection", skip_serializing_if = "Option::is_none")]
    pub ssl_connection: Option<bool>,
    /// __Filterable__ The Linode Instance type used by the Managed Database for its nodes.
    #[serde(rename = "type")]
    pub r#type: String,
}

impl PostDatabasesMysqlInstancesRequest {
    /// Managed MySQL Database request object.
    pub fn new(engine: String, label: String, region: String, r#type: String) -> PostDatabasesMysqlInstancesRequest {
        PostDatabasesMysqlInstancesRequest {
            allow_list: None,
            cluster_size: None,
            engine,
            fork: None,
            label,
            region,
            ssl_connection: None,
            r#type,
        }
    }
}
/// The number of Linode instance nodes deployed to the Managed Database.   - Choose `3` nodes to create a high availability cluster that consists of one primary node and two replica nodes.  - A `2` node cluster is only available with a dedicated plan. It consists of one primary node and one replica node.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ClusterSizeEnum {
    #[serde(rename = "1")]
    Variant1,
    #[serde(rename = "2")]
    Variant2,
    #[serde(rename = "3")]
    Variant3,
}

impl Default for ClusterSizeEnum {
    fn default() -> ClusterSizeEnum {
        Self::Variant1
    }
}

