/*
 * Akamai: Linode API
 *
 * Add a Cloud Computing instance so you can build, release, and scale applications faster with virtual machines. 
 *
 * The version of the OpenAPI document: 4.193.0
 * Contact: jperez@linode.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostCancelAccount409ResponseErrorsInner {
    /// A string explaining that the account could not be canceled because there is an outstanding balance on the account that must be paid first.
    #[serde(rename = "reason", skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
}

impl PostCancelAccount409ResponseErrorsInner {
    pub fn new() -> PostCancelAccount409ResponseErrorsInner {
        PostCancelAccount409ResponseErrorsInner {
            reason: None,
        }
    }
}

