/*
 * Akamai: Linode API
 *
 * Add a Cloud Computing instance so you can build, release, and scale applications faster with virtual machines. 
 *
 * The version of the OpenAPI document: 4.193.0
 * Contact: jperez@linode.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PostPayment202ResponseWarningsInner : An object for describing a single warning associated with a response.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostPayment202ResponseWarningsInner {
    /// Specific information related to the warning.
    #[serde(rename = "details", skip_serializing_if = "Option::is_none")]
    pub details: Option<String>,
    /// The general warning message.
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
}

impl PostPayment202ResponseWarningsInner {
    /// An object for describing a single warning associated with a response.
    pub fn new() -> PostPayment202ResponseWarningsInner {
        PostPayment202ResponseWarningsInner {
            details: None,
            title: None,
        }
    }
}

