/*
 * Akamai: Linode API
 *
 * Add a Cloud Computing instance so you can build, release, and scale applications faster with virtual machines. 
 *
 * The version of the OpenAPI document: 4.193.0
 * Contact: jperez@linode.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostRestoreBackupRequest {
    /// The ID of the Linode to restore a Backup to.
    #[serde(rename = "linode_id")]
    pub linode_id: i32,
    /// If `true`, deletes all Disks and Configs on the target Linode before restoring.  If `false`, and the Disk image size is larger than the available space on the Linode, an error message indicating insufficient space is returned.
    #[serde(rename = "overwrite", skip_serializing_if = "Option::is_none")]
    pub overwrite: Option<bool>,
}

impl PostRestoreBackupRequest {
    pub fn new(linode_id: i32) -> PostRestoreBackupRequest {
        PostRestoreBackupRequest {
            linode_id,
            overwrite: None,
        }
    }
}

