/*
 * Akamai: Linode API
 *
 * Add a Cloud Computing instance so you can build, release, and scale applications faster with virtual machines. 
 *
 * The version of the OpenAPI document: 4.193.0
 * Contact: jperez@linode.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostObjectStorageObjectUrl200Response {
    /// The signed URL to perform the request at.
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

impl PostObjectStorageObjectUrl200Response {
    pub fn new() -> PostObjectStorageObjectUrl200Response {
        PostObjectStorageObjectUrl200Response {
            url: None,
        }
    }
}

