/*
 * Akamai: Linode API
 *
 * Add a Cloud Computing instance so you can build, release, and scale applications faster with virtual machines. 
 *
 * The version of the OpenAPI document: 4.193.0
 * Contact: jperez@linode.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PostManagedContactRequest : Information about someone Linode's special forces may contact in case an issue is detected with a manager service.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostManagedContactRequest {
    /// The address to email this Contact to alert them of issues.
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    /// __Filterable__ A grouping for this Contact. This is for display purposes only.
    #[serde(rename = "group", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub group: Option<Option<String>>,
    /// __Read-only__ This Contact's unique ID.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// The name of this Contact.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "phone", skip_serializing_if = "Option::is_none")]
    pub phone: Option<models::GetManagedContacts200ResponseDataInnerPhone>,
    /// __Read-only__ When this Contact was last updated.
    #[serde(rename = "updated", skip_serializing_if = "Option::is_none")]
    pub updated: Option<String>,
}

impl PostManagedContactRequest {
    /// Information about someone Linode's special forces may contact in case an issue is detected with a manager service.
    pub fn new() -> PostManagedContactRequest {
        PostManagedContactRequest {
            email: None,
            group: None,
            id: None,
            name: None,
            phone: None,
            updated: None,
        }
    }
}

