/*
 * Akamai: Linode API
 *
 * Add a Cloud Computing instance so you can build, release, and scale applications faster with virtual machines. 
 *
 * The version of the OpenAPI document: 4.193.0
 * Contact: jperez@linode.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostDatabasesMysqlInstancesRequestFork {
    /// The database timestamp from which it was restored. This is _not_ when the fork was created.
    #[serde(rename = "restore_time", skip_serializing_if = "Option::is_none")]
    pub restore_time: Option<String>,
    /// The instance id of the database that was forked from.
    #[serde(rename = "source")]
    pub source: i32,
}

impl PostDatabasesMysqlInstancesRequestFork {
    pub fn new(source: i32) -> PostDatabasesMysqlInstancesRequestFork {
        PostDatabasesMysqlInstancesRequestFork {
            restore_time: None,
            source,
        }
    }
}

