/*
 * Akamai: Linode API
 *
 * Add a Cloud Computing instance so you can build, release, and scale applications faster with virtual machines. 
 *
 * The version of the OpenAPI document: 4.193.0
 * Contact: jperez@linode.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostRebootLinodeInstanceRequest {
    /// The Linode Config ID to reboot into.  If `null` or omitted, the last booted config will be used.  If there was no last booted config and this Linode only has one config, it will be used.  If a config cannot be determined, an error will be returned.
    #[serde(rename = "config_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub config_id: Option<Option<i32>>,
}

impl PostRebootLinodeInstanceRequest {
    pub fn new() -> PostRebootLinodeInstanceRequest {
        PostRebootLinodeInstanceRequest {
            config_id: None,
        }
    }
}

