/*
 * Akamai: Linode API
 *
 * Add a Cloud Computing instance so you can build, release, and scale applications faster with virtual machines. 
 *
 * The version of the OpenAPI document: 4.193.0
 * Contact: jperez@linode.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostAllocateIpRequest {
    /// The ID of a Linode you have access to that this address will be allocated to.
    #[serde(rename = "linode_id")]
    pub linode_id: i32,
    /// Whether to create a public or private IPv4 address.
    #[serde(rename = "public")]
    pub public: bool,
    /// The type of address you are requesting. Only IPv4 addresses may be allocated through this operation.
    #[serde(rename = "type")]
    pub r#type: TypeEnum,
}

impl PostAllocateIpRequest {
    pub fn new(linode_id: i32, public: bool, r#type: TypeEnum) -> PostAllocateIpRequest {
        PostAllocateIpRequest {
            linode_id,
            public,
            r#type,
        }
    }
}
/// The type of address you are requesting. Only IPv4 addresses may be allocated through this operation.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TypeEnum {
    #[serde(rename = "ipv4")]
    Ipv4,
}

impl Default for TypeEnum {
    fn default() -> TypeEnum {
        Self::Ipv4
    }
}

