/*
 * Akamai: Linode API
 *
 * Add a Cloud Computing instance so you can build, release, and scale applications faster with virtual machines. 
 *
 * The version of the OpenAPI document: 4.193.0
 * Contact: jperez@linode.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PostAssignIpsRequest : Request object for IP Addresses Assign (POST /networking/ips/assign).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostAssignIpsRequest {
    /// The list of assignments to make. You must have read_write access to all IPs being assigned and all Linodes being assigned to in order for the assignments to succeed.
    #[serde(rename = "assignments")]
    pub assignments: Vec<models::PostAssignIpsRequestAssignmentsInner>,
    /// The ID of the Region in which these assignments are to take place. All IPs and Linodes must exist in this Region.
    #[serde(rename = "region")]
    pub region: String,
}

impl PostAssignIpsRequest {
    /// Request object for IP Addresses Assign (POST /networking/ips/assign).
    pub fn new(assignments: Vec<models::PostAssignIpsRequestAssignmentsInner>, region: String) -> PostAssignIpsRequest {
        PostAssignIpsRequest {
            assignments,
            region,
        }
    }
}

