/*
 * Akamai: Linode API
 *
 * Add a Cloud Computing instance so you can build, release, and scale applications faster with virtual machines. 
 *
 * The version of the OpenAPI document: 4.193.0
 * Contact: jperez@linode.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PutLinodeConfigInterface200ResponseIpv4 : IPv4 addresses configured for this interface. Only applies to interfaces with a `purpose` of `vpc`. Returned as `null` if the interface has a `purpose` of `public` or `vlan`.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PutLinodeConfigInterface200ResponseIpv4 {
    /// The 1:1 NAT IPv4 address, used to associate a public IPv4 address with the interface's VPC subnet IPv4 address. This only applies to interfaces with a `purpose` of `vpc`. Returned as `null` if no 1:1 NAT is set for a `vpc` interface. Returned as an empty string (`\"\"`) if the interface has a `purpose` of `public` or `vlan`.
    #[serde(rename = "nat_1_1", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub nat_1_1: Option<Option<String>>,
    /// The VPC subnet IPv4 address for this interface. This only applies to interfaces with a `purpose` of `vpc`. Returned as an empty string (`\"\"`) if the interface has a `purpose` of `public` or `vlan`.
    #[serde(rename = "vpc", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub vpc: Option<Option<String>>,
}

impl PutLinodeConfigInterface200ResponseIpv4 {
    /// IPv4 addresses configured for this interface. Only applies to interfaces with a `purpose` of `vpc`. Returned as `null` if the interface has a `purpose` of `public` or `vlan`.
    pub fn new() -> PutLinodeConfigInterface200ResponseIpv4 {
        PutLinodeConfigInterface200ResponseIpv4 {
            nat_1_1: None,
            vpc: None,
        }
    }
}

