/*
 * Akamai: Linode API
 *
 * Add a Cloud Computing instance so you can build, release, and scale applications faster with virtual machines. 
 *
 * The version of the OpenAPI document: 4.193.0
 * Contact: jperez@linode.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PutObjectStorageKey200ResponseRegionsInner {
    /// Identifies each region where you can use the Object Storage key.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The S3-compatible hostname you can use to access your Object Storage buckets in this region.
    #[serde(rename = "s3_endpoint", skip_serializing_if = "Option::is_none")]
    pub s3_endpoint: Option<String>,
}

impl PutObjectStorageKey200ResponseRegionsInner {
    pub fn new() -> PutObjectStorageKey200ResponseRegionsInner {
        PutObjectStorageKey200ResponseRegionsInner {
            id: None,
            s3_endpoint: None,
        }
    }
}

