/*
 * Akamai: Linode API
 *
 * Add a Cloud Computing instance so you can build, release, and scale applications faster with virtual machines. 
 *
 * The version of the OpenAPI document: 4.193.0
 * Contact: jperez@linode.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PutLkeClusterRequestControlPlane : Defines settings for the Kubernetes control plane, including High Availability (HA) and an IP-based Access Control List (ACL) for the control plane components.  When upgrading pre-existing LKE clusters to use the HA Control Plane, the following changes will additionally occur:  - All nodes will be deleted and new nodes will be created to replace them.  - Any local storage (such as `hostPath` volumes) will be erased.  - The upgrade process may take several minutes to complete, as nodes will be replaced on a rolling basis.  When upgrading pre-existing LKE clusters to use the control plane ACL for the first time, it may take several hours for external clients to respect the access control settings. This is partly due to delays from DNS propagation.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PutLkeClusterRequestControlPlane {
    #[serde(rename = "acl", skip_serializing_if = "Option::is_none")]
    pub acl: Option<models::PutLkeClusterRequestControlPlaneAcl>,
    /// Enables High Availability for the cluster's control plane components. It defaults to `false`. Enabling High Availability for LKE is an irreversible change.
    #[serde(rename = "high_availability", skip_serializing_if = "Option::is_none")]
    pub high_availability: Option<bool>,
}

impl PutLkeClusterRequestControlPlane {
    /// Defines settings for the Kubernetes control plane, including High Availability (HA) and an IP-based Access Control List (ACL) for the control plane components.  When upgrading pre-existing LKE clusters to use the HA Control Plane, the following changes will additionally occur:  - All nodes will be deleted and new nodes will be created to replace them.  - Any local storage (such as `hostPath` volumes) will be erased.  - The upgrade process may take several minutes to complete, as nodes will be replaced on a rolling basis.  When upgrading pre-existing LKE clusters to use the control plane ACL for the first time, it may take several hours for external clients to respect the access control settings. This is partly due to delays from DNS propagation.
    pub fn new() -> PutLkeClusterRequestControlPlane {
        PutLkeClusterRequestControlPlane {
            acl: None,
            high_availability: None,
        }
    }
}

