/*
 * Akamai: Linode API
 *
 * Add a Cloud Computing instance so you can build, release, and scale applications faster with virtual machines. 
 *
 * The version of the OpenAPI document: 4.193.0
 * Contact: jperez@linode.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PutLkeClusterAclRequest : Defines settings for the Kubernetes control plane, including an IP-based Access Control List (ACL) for the control plane components.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PutLkeClusterAclRequest {
    #[serde(rename = "acl", skip_serializing_if = "Option::is_none")]
    pub acl: Option<models::PutLkeClusterAclRequestAcl>,
}

impl PutLkeClusterAclRequest {
    /// Defines settings for the Kubernetes control plane, including an IP-based Access Control List (ACL) for the control plane components.
    pub fn new() -> PutLkeClusterAclRequest {
        PutLkeClusterAclRequest {
            acl: None,
        }
    }
}

