/*
 * Akamai: Linode API
 *
 * Add a Cloud Computing instance so you can build, release, and scale applications faster with virtual machines. 
 *
 * The version of the OpenAPI document: 4.193.0
 * Contact: jperez@linode.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PutManagedLinodeSettingRequest : Settings for a specific Linode related to Managed Services. There is one ManagedLinodeSettings object for each Linode on your Account.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PutManagedLinodeSettingRequest {
    /// __Read-only__ The group of the Linode these Settings are for. This is for display purposes only.
    #[serde(rename = "group", skip_serializing_if = "Option::is_none")]
    pub group: Option<String>,
    /// __Read-only__ The ID of the Linode these Settings are for.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// __Read-only__ The label of the Linode these Settings are for.
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    #[serde(rename = "ssh", skip_serializing_if = "Option::is_none")]
    pub ssh: Option<models::PutManagedLinodeSettingRequestSsh>,
}

impl PutManagedLinodeSettingRequest {
    /// Settings for a specific Linode related to Managed Services. There is one ManagedLinodeSettings object for each Linode on your Account.
    pub fn new() -> PutManagedLinodeSettingRequest {
        PutManagedLinodeSettingRequest {
            group: None,
            id: None,
            label: None,
            ssh: None,
        }
    }
}

